name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger auf Tag-Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Setze dies auf deine .NET-Version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish --configuration Release --output ./output

    - name: Create a ZIP file for release
      run: |
        Compress-Archive -Path ./output/* -DestinationPath ./output/Release.zip

    - name: Upload Release ZIP
      uses: actions/upload-artifact@v3
      with:
        name: release-zip
        path: ./output/Release.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create GitHub Release
      uses: gh-actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: gh-actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/Release.zip
        asset_name: Release.zip
        asset_content_type: application/zip
